### PR TITLE
Fix Generic Junit Injection

### LINKED ISSUE #461: Injection of parameterized types doesn't work as expected
Hi everyone, I expericene a problem with injecting parameterized types. It seems avaje-inject is not able to find beans, if they have a type parameter even though the bean is present in the bean scope. For example I tried to define a bean of [MongoCollection](https://mongodb.github.io/mongo-java-driver/4.11/apidocs/mongodb-driver-sync/com/mongodb/client/MongoCollection.html) in a `@Factory` annotated configuration class via a `@Bean` annotated factory method:

```java
@Factory
class MyConfig {

    @Bean
    public MongoCollection<MyDocument> buildCollection() {
        // omitted for brevity
    }
}
```

Then I tried to inject the bean into my component test (I tried both using `@InjectTest` as well as programmatically creating the `BeanScope`).

The run fails with: `No bean found for type: ...` even though I can see the bean in the BeanScop, when debugging.

I was able to work around this issue by using the raw type in the definition of the factory method as well as when injecting the bean, but I'd rather not be forced to cast the object everytime:

```java
@Factory
class MyConfig {

    @Bean
    public MongoCollection buildCollection() {
        // omitted for brevity
    }
}
```

Did I miss something? Is this really the intended behavior?

### PR DESCRIPTION
**Pull request by SentryMan**
- Fix situations where generic types were not being properly injected into certain types of test
- Adds new default methods to make retrieving a generic bean more intuitive

resolves #461

### CODE REVIEW

File: blackbox-test-inject/src/test/java/org/example/myapp/generic/GenericFactoryTest.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+@InjectTest
+class GenericFactoryTest {
+
+  @Inject Generic<Integer> intymcintface;
+  @Inject Generic<String> stringy;
+
+  @Test
+  void test() {
+    assertThat(intymcintface).isNotNull();
+  }
```
Comment (rbygrave) [inline blackbox-test-inject/src/test/java/org/example/myapp/generic/GenericFactoryTest.java:19]: assert on stringy too

File: inject-test/src/test/java/io/avaje/inject/test/MetaReaderTest.java [hunk 2]
```diff
@@ -49,7 +50,7 @@ static class HelloBean {
 
   static class MyPlugin implements Plugin {
 
-    public boolean forType(Class<?> type) {
+  public boolean forType(Type type) {
```
Comment (rbygrave) [inline inject-test/src/test/java/io/avaje/inject/test/MetaReaderTest.java:53]: indentation, format only

File: inject/src/main/java/io/avaje/inject/BeanScope.java [hunk 3]
```diff
@@ -140,7 +141,51 @@ static BeanScopeBuilder builder() {
   <T> T get(Class<T> type, @Nullable String name);
 
   /**
-   * Return a single bean given the generic type and name.
+   * Return a single bean given its type and generic components.
+   *
+   * <pre>{@code
+   * Map<String, CoffeeMaker> coffeeMaker = beanScope.get(Map.class, String.class, CoffeeMaker.class);
```
Comment (rbygrave) [inline inject/src/main/java/io/avaje/inject/BeanScope.java:147]: This looks like extra functionality and not part of the bug fix?

Improve this example

File: inject/src/main/java/io/avaje/inject/BeanScope.java [hunk 4]
```diff
@@ -140,7 +141,51 @@ static BeanScopeBuilder builder() {
...
+   * heater.heat();
+   *
+   * }</pre>
+   *
+   * @param type an interface or bean type
+   * @param name the name qualifier of a specific bean
+   * @throws java.util.NoSuchElementException When no matching bean is found
+   */
+  default <T> T get(@Nullable String name, Type type, Type... types) {
+
```
Comment (rbygrave) [inline inject/src/main/java/io/avaje/inject/BeanScope.java:173]: whitespace formatting
This looks like extra functionality unrelated to the bug fix.

File: inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java [hunk 5]
```diff
@@ -196,6 +197,12 @@ private <D> BeanScopeBuilder.ForTesting spy(Class<D> type, @Nullable String name
     return this;
   }
 
+  private <D> BeanScopeBuilder.ForTesting spy(
+      Type type, @Nullable String name, @Nullable Consumer<D> consumer) {
```
Comment (rbygrave) [inline inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java:201]: formatting

File: inject/src/main/java/io/avaje/inject/spi/GenericTypeUtil.java [hunk 6]
```diff
@@ -56,7 +54,323 @@ static Type typeArgument(Class<?> clazz) {
       // needed type argument not supplied - break and throw exception
       break;
     }
-    throw new IllegalArgumentException(currentType + " does not specify the type parameter T of GenericType<T>");
+    throw new IllegalArgumentException(
```
Comment (rbygrave) [inline inject/src/main/java/io/avaje/inject/spi/GenericTypeUtil.java:57]: formatting, looks like no actual change here.

File: inject/src/main/java/io/avaje/inject/spi/GenericTypeUtil.java [hunk 7]
```diff
@@ -56,7 +54,323 @@ static Type typeArgument(Class<?> clazz) {
...
+        currentType + " does not specify the type parameter T of GenericType<T>");
+  }
+
+  /** Returns an array type whose elements are all instances of {@code componentType}. */
+  public static GenericArrayType arrayOf(Type elementType) {
```
Comment (rbygrave) [inline inject/src/main/java/io/avaje/inject/spi/GenericTypeUtil.java:62]: Looks like this has come in from avaje-jsonb.  Why is is added though?  Not part of bug fix per say.

File: inject/src/main/java/io/avaje/inject/spi/GenericTypeUtil.java [hunk 8]
```diff
@@ -56,7 +54,323 @@ static Type typeArgument(Class<?> clazz) {
...
+      throw new IllegalArgumentException("Unexpected primitive " + type + ". Use the boxed type.");
+    }
+  }
+
+  static final class ParameterizedTypeImpl implements ParameterizedType {
+    private final Type ownerType;
+    private final Type rawType;
+    public final Type[] typeArguments;
+
+    public ParameterizedTypeImpl(Type ownerType, Type rawType, Type... typeArguments) {
```
Comment (rbygrave) [inline inject/src/main/java/io/avaje/inject/spi/GenericTypeUtil.java:130]: remove public  modifier

File: inject/src/main/java/io/avaje/inject/spi/GenericTypeUtil.java (hunk 7 above)
Comment (rbygrave) [inline inject/src/main/java/io/avaje/inject/spi/GenericTypeUtil.java:62]: remove public modifier

File: inject/src/main/java/io/avaje/inject/spi/GenericTypeUtil.java [hunk 9]
```diff
@@ -56,7 +54,323 @@ static Type typeArgument(Class<?> clazz) {
...
+  /** Returns an array type whose elements are all instances of {@code componentType}. */
+  public static GenericArrayType arrayOf(Type elementType) {
+    return new GenericArrayTypeImpl(elementType);
+  }
+
+  /**
+   * Returns a new parameterized type, applying {@code typeArguments} to {@code rawType}. Use this
+   * method if {@code rawType} is not enclosed in another type.
+   */
+  public static ParameterizedType newParameterizedType(Type rawType, Type... typeArguments) {
```
Comment (rbygrave) [inline inject/src/main/java/io/avaje/inject/spi/GenericTypeUtil.java:70]: remove public modifier

File: inject/src/main/java/io/avaje/inject/spi/Types.java [hunk 10]
```diff
@@ -0,0 +1,75 @@
...
+
+  /** Return the raw type for the given potentially generic type. */
+  public static Class<?> rawType(Type type) {
+    if (type instanceof Class<?>) {
+      // type is a normal class.
+      return (Class<?>) type;
+
+    } else if (type instanceof ParameterizedType) {
+      ParameterizedType parameterizedType = (ParameterizedType) type;
+
```
Comment (rbygrave) [inline inject/src/main/java/io/avaje/inject/spi/Types.java:51]: whitespace

File: inject/src/main/java/io/avaje/inject/spi/Types.java [hunk 11]
```diff
@@ -0,0 +1,75 @@
...
+      return Array.newInstance(rawType(componentType), 0).getClass();
+
+    } else if (type instanceof TypeVariable) {
+      return Object.class;
+
+    } else if (type instanceof WildcardType) {
+      return rawType(((WildcardType) type).getUpperBounds()[0]);
+
+    } else {
+
```
Comment (rbygrave) [inline inject/src/main/java/io/avaje/inject/spi/Types.java:66]: whitespace

**Review by rbygrave — COMMENTED** [review]
Still reviewing ...
