### PR TITLE
Fix Lazy Priority Generation

### LINKED ISSUE #936: @Primary ignored when @Lazy present
### Environment
avaje-inject: 12.0
Java: 25

### Single-File Reproducer
SpanishGreeting is marked as @Primary but EnglishGreeting gets injected instead. If I remove @Lazy(Lazy.Kind.PROVIDER) from the classes, SpanishGreeting gets injected correctly.
```java
import io.avaje.inject.BeanScope;
import io.avaje.inject.Lazy;
import io.avaje.inject.Primary;
import jakarta.inject.Singleton;

interface GreetingService {
  String greet();
}

@Lazy(Lazy.Kind.PROVIDER)
@Singleton
class EnglishGreeting implements GreetingService {
  @Override public String greet() { return "Hello"; }
}

@Primary
@Lazy(Lazy.Kind.PROVIDER)
@Singleton
class SpanishGreeting implements GreetingService {
  @Override public String greet() { return "Hola"; }
}

@Lazy(Lazy.Kind.PROVIDER)
@Singleton
class Greeter {
  private final GreetingService service;
  Greeter(GreetingService service) { this.service = service; }
  String run() { return service.greet(); }
}

// Minimal test/runner
public class PrimaryLazyRepro {
  public static void main(String[] args) {
    try (var scope = BeanScope.builder().build()) {
      var greeter = scope.get(Greeter.class);
      String actual = greeter.run();
      System.out.println("Selected: " + actual);
      if (!"Hola".equals(actual)) {
        throw new IllegalStateException("Expected @Primary to be selected, got: " + actual);
      }
    }
  }
}
```

### Question
Is this the intended behavior when using @Lazy, or is it a bug?

### PR DESCRIPTION
**Pull request by SentryMan**
It seems that the `asPrimary` code was not getting generated.

resolves #936

### CODE REVIEW

File: inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java [hunk 1]
```diff
@@ -186,7 +187,9 @@ private void writeAddFor(MethodReader constructor) {
         registerProvider = "asPrototype().registerProvider";
       }
 
-      writer.append("      builder.%s(() -> {", registerProvider).eol();
```
Comment (rbygrave) [inline inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java]: bug here, missing priorities ...
