### PR TITLE
Multi-Scope Wiring

### LINKED ISSUE #793: Cross-/multi-scope bean wiring
Hi there! I'm experimenting with avaje-inject version 11.4 and exploring ways to work with `@Scopes` in order to make a mono-repo with multiple deployments, which share a lot of common code by virtue of sharing a common core and because it was previously a monolith.

Ideally, there'd be an easy way to:
 * Annotate each component with a small number of annotations, which defines which deployments it's applicable to
 * Easily start the application with a small "main" method

I've tried a few things, but have gotten stuck on these paths (code examples+more detail in the expandables):

<details>
<summary>Declare scopes requiring other scopes, automatically including them</summary>

Using the following structure:

```java
@Scope
@InjectModule(provides = {BeanInModA.class}, strictWiring = true)
public @interface ModAScope {}

@ModAScope
public class BeanInModA{}

@Scope
@InjectModule(provides = {BeanInModB.class}, strictWiring = true)
public @interface ModBScope {}

@ModBScope
public class BeanInModB{}

@Scope
@InjectModule(requires = {ModAScope.class, ModBScope.class}, strictWiring = true)
public @interface CrossCutScope {}

@CrossCutScope
public class BeanCross{
    public BeanCross(final BeanInModA beanInModA, final BeanInModB beanInModB) {

    }
}
```

The result means you cannot just refer to the `CrossCutModule` when starting an entire `BeanScope` - you have to declare parent scopes (which is documented), or start the `BeanScope` with all modules declared in order. You can't pass them to `BeanScope.builder().modules(...)` out of order (e.g. `ModAScope, CrossCutScope, ModBScope`) as you'll end up with exception at startup ("`java.lang.IllegalStateException`: Injecting null for `com.example.BeanInModB name:!beanInModB` ..."). 

This is fine if you have a small number of scopes with a clear parent/child hierarchy, but if you have a large number of scopes/modules, or there's not a clear relationship between them, it becomes quite unmanageable.

---

</details>
<details>
<summary>Meta-annotating defined Scopes</summary>

Using the following structure:

```java
@Scope
@Target(TYPE)
@Retention(SOURCE)
@InjectModule(strictWiring = true)
public @interface ModAScope {}

@Scope
@Target(TYPE)
@Retention(SOURCE)
@InjectModule(strictWiring = true)
public @interface ModBScope {}

@ModAScope
@ModBScope
@Target(TYPE)
@Retention(SOURCE)
public @interface MetaScope {}

@MetaScope
public class MyBean {}
```

I hoped it would result in the same output as:

```java
@ModAScope
@ModBScope
public class MyBean {}
```

So the bean exists in both `ModAScope` and `ModBScope`, but instead it's not picked up by Avaje at all.

---

</details>

While `@Profile` would probably do what I need (and I can meta-annotate those), that's less easily shaded (in the sense of dropping unreferenced classes) and doesn't give compile time errors. While neither of those cons are deal-breakers (Avaje is fast and light enough from my experiments you can just check the profiles work in tests, and there's negligible runtime overhead to non-constructed beans) I'm surprised that neither of my scope attempts worked (and at the `BeanScope.builder().modules(...)` being order-dependent). Another option would be to have many Gradle/Maven sub-projects and rely on the default scope, but that would also become quite unwieldy depending on the size of the code base and how much you wish to split it.

Is there any scope/intention to support something like this with `@Scope`/`@InjectModule`? Ideas on making something like this work without introducing potentially breaking changes:
 1. Add another value to the `InjectModule` called something like `automaticallyImport` which acts like `requires` for all validation checking, but when the generated module's `build` method is called the first operations are to create and build the listed modules/scopes
 2. Add an option on the `BeanScopeBuilder` to correct module order (default `false` - current behaviour) and/or to define our own `ModuleOrdering` with custom logic
 3. Allow `Scope` composite annotations. A bean annotated with a meta-scope would be treated as if it were directly annotated with those scopes, which currently is to be created in each scope.

Option 3 is probably the most elegant for both Avaje and consuming applications. A blend of Options 1 and 2 could also be done outside of Avaje as the details are available at run-time, so someone using Avaje could write a method that takes in a module and it returns an array of modules in the correct order (if an order is possible).

Thanks heaps for taking the time to read!

### PR DESCRIPTION
**Pull request by SentryMan**
@cbarlin would this suffice?

With this, you would have to add the `requires` property in your `@InjectModule` annotations to control the order.

- now will order manually provided `AvajeModule`s
- will generate an `allRequiredModules` static method if the module has no external project scope dependencies and no transitive constructor params

Resolves #793

### CODE REVIEW

**Comment by cbarlin** [comment]
Looks great! Checking it out locally I can make it work with `strictWiring = true` on them as well (and make it work with a mix of some with and some without), if we wanted to add those to the test cases.

But yeah that solves the ordering problem nicely :)

**Comment by cbarlin** [comment]
Thanks heaps @SentryMan! Did you want me to leave those other two PRs up?

File: blackbox-multi-scope/src/main/java/org/multi/scope/CrossCutScope.java [hunk 1]
```diff
@@ -2,9 +2,9 @@
...
 import jakarta.inject.Scope;
-import org.multi.modb.BeanInModB;
 
 @Scope
-@InjectModule(requires = {ModAScope.class, ModBScope.class}, strictWiring = true)
-public @interface CrossCutScope {
-}
+@InjectModule(
+    requires = {ModAScope.class, ModBScope.class},
+    provides = CrossCutScope.class)
```
Comment (rbygrave) [inline blackbox-multi-scope/src/main/java/org/multi/scope/CrossCutScope.java:9]: To me the `provides` should **_not_** be needed ultimately. To me we've needed to add them here ... but ultimately that wouldn't be desirable.

File: blackbox-multi-scope/src/test/java/org/multi/crosscut/BeanCrossTest.java [hunk 2]
```diff
@@ -1,24 +1,97 @@
...
 
-import static org.assertj.core.api.Assertions.assertThat;
+import io.avaje.inject.BeanScope;
+import io.avaje.inject.spi.AvajeModule;
 
 class BeanCrossTest {
 
-  @Test
-  void bootstrap() {
+  private static Stream<Arguments> allModulesDefined() {
```
Comment (rbygrave) [inline blackbox-multi-scope/src/test/java/org/multi/crosscut/BeanCrossTest.java:32]: IMO these tests are not what we ergonomically desire/need.

That is, we want to say "Give me all the modules that I need for CrossCutModule [and ideally give them in the correct order]" ... and use those to create a BeanScope.

These tests are more just ... we can order the given list of modules correctly.

Comment (SentryMan) [reply blackbox-multi-scope/src/test/java/org/multi/crosscut/BeanCrossTest.java:32]: > These tests are more just ... we can order the given list of modules correctly.

do we have an existing test for that?

File: blackbox-multi-scope/src/main/java/org/multi/scope/CrossCutScope.java (hunk 1 above)
Comment (SentryMan) [reply blackbox-multi-scope/src/main/java/org/multi/scope/CrossCutScope.java:9]: Would auto-providing the scope annotation suffice?

**Comment by SentryMan** [comment]
Now you need only the requires property

**Comment by cbarlin** [comment]
Looks awesome - thank you so much!

**Review by rbygrave — APPROVED** [review]
