### PR TITLE
Fix injecting generic types extending generic types

### LINKED ISSUE #764: Bugs when dependency using generic types
my di class

```java
@Factory
public class DIKafka {

  @Bean
  KafkaProducer<String, String> provideKafkaProducer(@External Vertx vertx, @External YmlJsonObject config) {
    // kafka producer
    val servers = config.getJsonArray(Constant.Text.KAFKA_SERVERS).stream().map(String::valueOf).toList();
    val kafkaProducerMap = new HashMap<String, String>();
    kafkaProducerMap.put(Constant.Text.BOOTSTRAP_SERVERS, String.join(",", servers));
    kafkaProducerMap.put(Constant.Text.KEY_SERIALIZER, Constant.Text.KAFKA_STRING_SERIALIZER);
    kafkaProducerMap.put(Constant.Text.VALUE_SERIALIZER, Constant.Text.KAFKA_STRING_SERIALIZER);

    val extraConfig = config.getJsonObject(Constant.Text.KAFKA_PRODUCER_PROPS).stream()
      .map(entry -> Map.entry(entry.getKey(), String.valueOf(entry.getValue())))
      .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
    kafkaProducerMap.putAll(extraConfig);

    return KafkaProducer.create(vertx, kafkaProducerMap);
  }
}
```
Generated class by DI
```java
@Generated("io.avaje.inject.generator")
public final class DIKafka$DI  {

  public static final Type TYPE_KafkaProducerStringString =
      new GenericType<KafkaProducer<String, String>>(){}.type();
  public static final Type TYPE_WriteStreamKafkaProducerRecord =
      new GenericType<WriteStream<KafkaProducerRecord<K, V>>>(){}.type();

  public static void build(Builder builder) {
    if (builder.isBeanAbsent(DIKafka.class)) {
      var bean = new DIKafka();
      builder.register(bean);
    }
  }

  /**
   * Create and register KafkaProducer via factory bean method DIKafka#provideKafkaProducer().
   */
  public static void build_provideKafkaProducer(Builder builder) {
    if (builder.isBeanAbsent(TYPE_KafkaProducerStringString, TYPE_WriteStreamKafkaProducerRecord, StreamBase.class)) {
      var factory = builder.get(DIKafka.class);
      var bean = factory.provideKafkaProducer(builder.get(Vertx.class,"!vertx"), builder.get(YmlJsonObject.class,"!config"));
      builder.register(bean);
    }
  }

}
```
[KafkaProducer.class](https://github.com/vert-x3/vertx-kafka-client/blob/master/src/main/java/io/vertx/kafka/client/producer/KafkaProducer.java)
```java
public interface KafkaProducer<K, V> extends WriteStream<KafkaProducerRecord<K, V>> {
```

this code error `java public static final Type TYPE_WriteStreamKafkaProducerRecord =
      new GenericType<WriteStream<KafkaProducerRecord<K, V>>>(){}.type();`

because the K, V must be String, String like `public static final Type TYPE_KafkaProducerStringString =
      new GenericType<KafkaProducer<String, String>>(){}.type();`

### PR DESCRIPTION
**Pull request by SentryMan**
fixes #764 

---- 

Edit: Noting that the issue was in the isAddGenericType() method that didn't _recursively_ check meaning that it didn't detect generic parameter types beyond the _"first level"_ of a generic type. With this fix it now checks recursively.

### CODE REVIEW

**Comment by SentryMan** [comment]
@rbygrave please release an RC when you get time

File: inject-generator/src/main/java/io/avaje/inject/generator/TypeAppender.java [hunk 1]
```diff
@@ -21,22 +22,31 @@ final class TypeAppender {
...
   }
 
-  private static boolean isAddGenericType(UType type, List<UType> components) {
+  private static boolean isAddGenericType(UType type) {
+    var components = type.componentTypes();
     return type.isGeneric()
       && type.kind() != TypeKind.TYPEVAR
       && (components.size() != 1 || components.get(0).kind() != TypeKind.WILDCARD)
       && components.stream()
+      .flatMap(TypeAppender::allComponentTypes)
```
Comment (rbygrave) [inline inject-generator/src/main/java/io/avaje/inject/generator/TypeAppender.java:38]: Noting that this is effectively the fix here.

**Review by rbygrave — APPROVED** [review]
